# Remote state backend configuration for dev environment
# Auto-generated by setup-terraform-backend.ps1 on 08/25/2025 21:07:32
resource_group_name  = "tripradar-tfstate-rg"
storage_account_name = "tripradartfstate250825"
container_name       = "tfstate"
key                  = "tripradar-dev.tfstate"
