#!/bin/bash
set -e

# Configuration
PROJECT="tripradar"
LOCATION="northeurope"
ENVIRONMENT=${1:-"dev"}

# Generate names
RG_NAME="${PROJECT}-tfstate-rg"
SA_NAME="${PROJECT}tfstate$(date +%s | tail -c 6)" # Append timestamp for uniqueness
CONTAINER_NAME="tfstate"

echo "🚀 Setting up Terraform backend for ${PROJECT}-${ENVIRONMENT}"
echo "Resource Group: ${RG_NAME}"
echo "Storage Account: ${SA_NAME}"
echo "Container: ${CONTAINER_NAME}"

# Check if logged into Azure
if ! az account show >/dev/null 2>&1; then
    echo "❌ Not logged into Azure. Please run 'az login' first."
    exit 1
fi

# Create Resource Group
echo "📦 Creating resource group..."
az group create \
    --name "${RG_NAME}" \
    --location "${LOCATION}" \
    --tags "Project=${PROJECT}" "Purpose=TerraformState"

# Create Storage Account
echo "💾 Creating storage account..."
az storage account create \
    --resource-group "${RG_NAME}" \
    --name "${SA_NAME}" \
    --location "${LOCATION}" \
    --sku "Standard_LRS" \
    --kind "StorageV2" \
    --allow-blob-public-access false \
    --https-only true \
    --tags "Project=${PROJECT}" "Purpose=TerraformState"

# Create Container
echo "📂 Creating blob container..."
az storage container create \
    --account-name "${SA_NAME}" \
    --name "${CONTAINER_NAME}" \
    --auth-mode login

# Update backend.hcl
BACKEND_FILE="infra/terraform/environments/${ENVIRONMENT}/app/backend.hcl"
echo "✏️  Updating ${BACKEND_FILE}..."

cat > "${BACKEND_FILE}" << EOF
# Remote state backend configuration for ${ENVIRONMENT} environment
# Auto-generated by setup-terraform-backend.sh on $(date)
resource_group_name  = "${RG_NAME}"
storage_account_name = "${SA_NAME}"
container_name       = "${CONTAINER_NAME}"
key                  = "tripradar-${ENVIRONMENT}.tfstate"
EOF

echo "✅ Terraform backend setup complete!"
echo ""
echo "📋 Configuration created:"
echo "  Resource Group: ${RG_NAME}"
echo "  Storage Account: ${SA_NAME}"
echo "  Container: ${CONTAINER_NAME}"
echo "  Backend file: ${BACKEND_FILE}"
echo ""
echo "🔧 Next steps:"
echo "1. Commit the updated backend.hcl file"
echo "2. Re-run your GitHub Actions workflow"
echo "3. The OIDC identity will need Storage Blob Data Contributor access to this storage account"
