name: PR Quality Gate

on:
  pull_request:
    branches: [ development, main ]
    types: [ opened, synchronize, reopened ]

jobs:
  quality-gate:
    name: 🛡️ PR Quality Gate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    # Enforce conventional commits
    - name: 🔍 Conventional Commits Check
      run: |
        echo "🔍 Checking commit message format..."

        # Get commit messages from the PR
        commits=$(git log --oneline --no-merges HEAD~${{ github.event.pull_request.commits }}..HEAD 2>/dev/null || git log --oneline --no-merges -10 2>/dev/null || echo "")

        if [ -z "$commits" ]; then
          echo "✅ No commits found to check"
          exit 0
        fi

        echo "📝 Found commits:"
        echo "$commits"
        echo ""

        # Check each commit message
        echo "$commits" | while read -r commit; do
          # Extract commit message (remove hash)
          commit_msg=$(echo "$commit" | cut -d' ' -f2-)

          # Skip if empty
          if [ -z "$commit_msg" ]; then
            continue
          fi

          echo "🔍 Checking: $commit_msg"

          # Check if it contains "dependabot" - allow these
          if echo "$commit_msg" | grep -q "dependabot"; then
            echo "✅ Dependabot commit - allowed"
            continue
          fi

          # Check if it contains "Merge" - allow these
          if echo "$commit_msg" | grep -q "^Merge"; then
            echo "✅ Merge commit - allowed"
            continue
          fi

          # Check basic conventional commit format
          if echo "$commit_msg" | grep -qE "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|infra|security)(\(.+\))?: "; then
            echo "✅ Valid conventional commit format"
          else
            echo "❌ Invalid commit format. Expected: type(scope): description"
            echo "   Valid types: build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test, infra, security"
            exit 1
          fi
        done

        echo "✅ All commits follow conventional format!"

    # Validate Terraform
    - name: 🏗️ Terraform Validation
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "~1.6.0"

    - name: Terraform Format Check
      run: |
        cd infra/terraform/environments/dev/app
        terraform fmt -check -recursive

    - name: Terraform Validate
      run: |
        cd infra/terraform/environments/dev/app
        terraform validate

    # PR Size Check
    - name: 📏 PR Size Check
      uses: codacy/git-version@2.8.6
      with:
        release-branch: main
        dev-branch: development

    - name: Comment PR Size
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const additions = pr.additions;
          const deletions = pr.deletions;

          let size = 'small';
          let color = 'green';

          if (additions + deletions > 1000) {
            size = 'large';
            color = 'red';
          } else if (additions + deletions > 100) {
            size = 'medium';
            color = 'yellow';
          }

          const body = `## 📊 PR Size Analysis
          - **Size**: ${size} (${color})
          - **Lines added**: +${additions}
          - **Lines deleted**: -${deletions}
          - **Total changes**: ${additions + deletions}

          ${size === 'large' ? '⚠️ Large PR detected. Consider breaking into smaller PRs.' : '✅ PR size looks good!'}
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
