name: Security Scan

on:
  push:
    branches: [ development, main ]
    paths: [ 'infra/terraform/**', 'src/**', 'Dockerfile*' ]
  pull_request:
    branches: [ development, main ]

jobs:
  # Security scan for Terraform
  terraform-security:
    name: 🔒 Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Checkov - Infrastructure Security Scan
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: infra/terraform/
        framework: terraform
        output_format: cli
        check: CKV_AZURE_*

    - name: TFSec - Infrastructure Security Scan
      uses: aquasecurity/tfsec-action@v1.28.4
      with:
        working_directory: infra/terraform/
        format: default

  # Security scan for Docker images
  trivy-scan:
    name: 🐳 Docker Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
