name: Shellcheck

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  shellcheck:
    name: ShellCheck (.sh)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    - name: Lint shell scripts
      shell: bash
      run: |
        set -euo pipefail
        SH_FILES="$(git ls-files '*.sh' | grep -E '(scripts/|/tf\.sh$)' | tr '\n' ' ')"
        if [ -z "$SH_FILES" ]; then
          echo "No .sh files to lint in scripts folder."
          exit 0
        fi
        echo "Linting files: $SH_FILES"
        shellcheck -S style -x $SH_FILES

  pssa:
    name: PSScriptAnalyzer (.ps1)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force
    - name: Lint PowerShell scripts
      shell: pwsh
      run: |
        $files = (git ls-files *.ps1 | Where-Object { $_ -match 'scripts/' -or $_ -match 'tf\.ps1$' })
        if (-not $files) {
          Write-Host "No .ps1 files to lint in scripts folder."
          exit 0
        }
        Write-Host "Linting files:`n$($files -join "`n")"
        Invoke-ScriptAnalyzer -Path $files -Recurse -EnableExit
